### ISSUE TITLE
ANTLR MSBuild error: Duplicate items are not supported by the “Sources” parameter

### ISSUE THREAD

**Issue by SheaCodes** [tunnelvisionlabs/antlr4cs#247]
I'm posting this partly because I want to learn more about MSBuild and partly in the hope that other's don't spend as much time as I did find the solution (google searches of the error text were not helpful in my case).

I recently upgraded to Visual Studio 2017. It would crash on occasion (and subsequently every time that particular .sln was loaded). My workaround was to launch the same .sln in Visual Studio 2015, compile (which would fail due to C# 7 features), after which Visual Studio 2017 would load the solution correctly.

This eventually reached an unacceptable annoyance threshold. The event log contained Visual Studio 2017 crash entries with the following exception:

**Exception Info: System.IO.FileLoadException at Antlr4.Build.Tasks.AntlrClassGenerationTaskInternal.HandleOutputDataReceived(System.Object, System.Diagnostics.DataReceivedEventArgs)**

A google search revealed that an upgrade to a later version of ANTLR was required: https://github.com/tunnelvisionlabs/antlr4cs/issues/173

After upgrading from 4.3.0 to 4.6.4, Visual Studio 2017 was no longer crashing but I received the following error on build:

**The item "(omitted)Lexer.cs" was specified more than once in the "Sources" parameter. Duplicate items are not supported by the "Sources" parameter.**

The *.cs files generated by ANTLR were getting included (at least) twice in the build process. After learning many, many ways not to fix the problem I eventually fixed the problem by removing the following lines at the bottom of the Antlr4.CodeGenerator.targets file:

```
<ItemGroup>
  <Compile Include="@(Antlr4GeneratedCodeFiles)" />
  <!-- The WinFX "GenerateTemporaryTargetAssembly" target requires generated code files be added here. -->
  <_GeneratedCodeFiles Include="@(Antlr4GeneratedCodeFiles)" />
</ItemGroup>
```

Does anybody know what else was including those files in the build? (This is my question)

(The project contains WPF User Controls and the intermediate "g.cs" etc. files are also located in the IntermediateOutputDirectory and would have to be included in the build which is my best guess).

If it is possible to conditionally include *.cs files in a build it might be worth modifying the default Antlr4.CodeGenerator.targets file to that effect.

**Comment by sharwell** [comment]
@SheaCodes Can you send me a copy of your project file, either in a comment on this issue or by email? I don't need the whole project, just the project file.

**Comment by sharwell** [comment]
@SheaCodes If you can't send it, let me know so I can ask all my questions about it here (could take a bit this way though).

**Comment by SheaCodes** [comment]
I would be happy to send via email - to what address should I send it?

**Comment by sharwell** [comment]
@SheaCodes Fascinating pro-tip: Git users submit commits with email addresses. Sometimes the address will say to not contact them, but not always. GitHub hides this information from the UI, e.g. you can't see it if you view tunnelvisionlabs/antlr4cs@7f3d302739417bc2d21f01b3a1012a8af0abef6d. However, the **patch** format for viewing diffs retains this information. You can request it explicitly by appending `?format=patch` to the URI of any single commit on GitHub.

Hopefully the obscurity of that description is compensated by its overall usefulness in case you're ever interested in something similar in the future. :smile:

**Comment by SheaCodes** [comment]
Cool! Sent. Let's hope the NLP of spambots doesn't evolve to the point where it can comprehend and follow those directions :)

**Comment by sharwell** [comment]
The underlying cause of the problem is the use of the following in the project file:

```xml
<Compile Include="Path\To\Generated\(omitted)Lexer.cs" />
```

This conflicts with the files automatically added by the build tools.

My primary recommendation is to remove all modifications to **Antlr4.CodeGenerator.targets**, as they currently are defeating intentional features of it. As a alternative, you can instead try changing the explicit `<Compile>` element for the generated files to be a `<None>` element. They will still show in Solution Explorer but will not cause problems for the compiler.

**Comment by SheaCodes** [comment]
If I remove:

    <Compile Include="Path\To\Generated\(omitted)Lexer.cs" />

from the project file and restore **Antlr4.CodeGenerator.targets** to its original state I get the original **"Duplicate items are not supported by the “Sources” parameter"** error on build.

I had tried that, previously - I still think that something is adding the auto-generated files more than once. Compilation succeeds again if I change the explicit `<Compile>` element to be a `<None>` element (on the surface, appears to be the same behavior as removing the `<ItemGroup>` element as per my original question).

**Comment by sharwell** [comment]
> If I remove ... from the project file ...

Note that you would need to remove all duplicates, including the listener, visitor, and parser files. The lexer was just one of the duplicates.

> and restore Antlr4.CodeGenerator.targets to its original state

By that I mean the contents should match [this file](https://github.com/tunnelvisionlabs/antlr4cs/blob/v4.6.4/runtime/CSharp/Antlr4BuildTasks/Antlr4.net40.targets) exactly. I noticed some customizations in the file that aren't mentioned above, and was suggesting those should be reverted as well.

**Comment by sharwell** [comment]
> I still think that something is adding the auto-generated files more than once. 

I'm going to see if there's a way we can test this.

**Comment by sharwell** [comment]
Thanks, do you know what version of Visual Studio 2017 you are using (e.g. 15.2, or 15.3.3)?

**Comment by SheaCodes** [comment]
I do - 15.3.3.

**Comment by mariodvm** [comment]
I have exactly the same problem, also I have VS 2017 v15.3.3

**Comment by sharwell** [comment]
I was able to reproduce this.

* It appears to only occur when building inside Visual Studio (not on the command line)
* It appears to only occur when you have an Antlr4 item and a Page item (WPF) in the same project

**Comment by mariodvm** [comment]
I was using WPF app, yes. I changed to Console application and it is already working!
Thanks

**Comment by sharwell** [comment]
> I recently upgraded to Visual Studio 2017. It would crash on occasion (and subsequently every time that particular .sln was loaded). My workaround ...

@SheaCodes I get a daily report telling me how many times this happens, but due to privacy policy it only contains a number of occurrences (yesterday was 4) and I have no way to tell anyone it's fixed. 😆

**Comment by SheaCodes** [comment]
Damn. Well, at least now there is a relatively easy path of bread crumbs to follow to the solution...

(Given that people might want to mix ANTLR and WPF in the same project, is the recommended solution to change the `<Compile>` element to `<None>` in the **Antlr4.CodeGenerator.targets** file as per your comment above?)

**Comment by sharwell** [comment]
So the underlying issue was caused by 5e40358823eb5a9115260b82c90bd5a41f6ea8d2 and then later fixed in bcad85aef14d1df6b0a4fefe6ee67fc4adbeb109. In the legacy project system, `$(BuildingProject)` is initially set to false and later set to true within a `<Target>`. This means it can only be referenced accurately by conditions also placed in a `<Target>`.

The good news for you today is the fix is already available. You can update just the **Antlr4.CodeGenerator** NuGet package to 4.6.5-beta0001, but keep the runtime at 4.6.4.

**Comment by kl1mm** [comment]
You forgot to include your bugfix in the release 4.6.5 - it's included in beta0001 and rc002

**Comment by sharwell** [comment]
@kl1mm The bug fix for the issue described in https://github.com/tunnelvisionlabs/antlr4cs/issues/247#issuecomment-328124229 was included in the 4.6.5 release. If you are experiencing similar symptoms, it would be due to something else so we would start with creating a new issue for that. 😄

**Comment by lukemurray** [comment]
@sharwell not sure if this is related. But I had these packages

```    <PackageReference Include="Antlr4" Version="4.6.5-rc002" />
    <PackageReference Include="Antlr4.Runtime" Version="4.6.5-rc002" />```

And this 
```<ItemGroup>
    <Antlr4 Include="grammer.g4">
      <Generator>MSBuild:Compile</Generator>
      <CustomToolNamespace>blah.Grammer</CustomToolNamespace>
      <Listener>False</Listener>
      <Visitor>True</Visitor>
    </Antlr4>
  </ItemGroup>```

in my dotnet core project file.
(this is a seperate issue) I was getting this error `error CS3021: 'GrammerLexer' does not need a CLSCompliant attribute because the assembly does not have a CLSCompliant attribute`

So I was actually copying the files into my project directory (out of obj) and editing those files (remvoing `[System.CLSCompliant(false)]`). I would then comment out the `Antlr4` element in the project file so it would not automatically generate the files.

If I upgrade to `4.6.5` commenting out the `Antlr4` element _still_ generates the grammer files. So I though, cool, I'll just not include them in my project and let it generate them each time.

Then I get the same error message above

`error MSB3105: The item "obj/Debug/netstandard1.6/GrammerLexer.cs" was specified more than once in the "Sources" parameter.  Duplicate items are not supported by the "Sources" parameter.`

Not `GrammerLexer` is not defined anywhere else, not a `class` nor a `filename`.

Right now I'm sticking with `4.6.5-rc002` and my manual step to generate the files.

Cheers,

**Comment by sharwell** [comment]
@lukemurray You need to add the following somewhere in your project:

```csharp
[assembly: CLSCompliant(false)]
```

I normally place this in an **AssemblyInfo.cs** file, which under the new project system might *only* contain the attribute here since the others are often generated during the build for these projects.

**Comment by flaksirus** [comment]
I have the same problem with really simple project (similar to my primary project): [testAntlr.zip](https://github.com/tunnelvisionlabs/antlr4cs/files/2400815/testAntlr.zip)
Problem discovered when I tried to use dotnet core sdk 2.1 instead of 2.0 and after updating nuget package from 4.6.4 to 4.6.5 (on 4.6.4 there were another build errors). 
The errors are similar on both platforms windows and linux (I used docker image microsoft/dotnet:2.1-sdk):
```
C:\Program Files\dotnet\sdk\2.1.400\Roslyn\Microsoft.CSharp.Core.targets(52,5): error MSB3105: The item "C:\Repositories\testAntlr\obj\Debug\netstandard2.0\GrammarHelloLexer.cs"
was specified more than once in the "Sources" parameter.  Duplicate items are not supported by the "Sources" parameter. [C:\Repositories\testAntlr\testAntlr.csproj]
    0 Warning(s)
    1 Error(s)
```
In `obj/Debug/netstandart2.0/testAntlr.csproj.Antlr4GeneratedCodeFileListAbsolute` file list are indeed duplicated:
```
/testAntlr/obj/Debug/netstandard2.0/GrammarHelloLexer.cs
/testAntlr/obj/Debug/netstandard2.0/GrammarHelloParser.cs
/testAntlr/obj/Debug/netstandard2.0/GrammarHelloListener.cs
/testAntlr/obj/Debug/netstandard2.0/GrammarHelloBaseListener.cs
/testAntlr/obj/Debug/netstandard2.0/GrammarHelloVisitor.cs
/testAntlr/obj/Debug/netstandard2.0/GrammarHelloBaseVisitor.cs
/testAntlr/obj/Debug/netstandard2.0/GrammarHelloLexer.cs
/testAntlr/obj/Debug/netstandard2.0/GrammarHelloParser.cs
/testAntlr/obj/Debug/netstandard2.0/GrammarHelloListener.cs
/testAntlr/obj/Debug/netstandard2.0/GrammarHelloBaseListener.cs
/testAntlr/obj/Debug/netstandard2.0/GrammarHelloVisitor.cs
/testAntlr/obj/Debug/netstandard2.0/GrammarHelloBaseVisitor.cs
```
I tried place `[assembly: CLSCompliant(false)]` in my code but it's not worked for me.

**Comment by sharwell** [comment]
@flaksirus Your issue is caused by the new feature that automatically includes grammar files when using the new project system, the same way C# source files are automatically included. Changing instances of `<Antlr4 Include="..."` in your project file to `<Antlr4 Update="..."` will fix the issue. Or you can disable the feature altogether by setting the `EnableDefaultAntlrItems` property as described in the [4.6.5-beta002](https://github.com/tunnelvisionlabs/antlr4cs/releases/tag/v4.6.5-beta002) release notes.

**Comment by flaksirus** [comment]
Indeed, I tried it before and it didn't worked for me, but now I'm realized that I haven't cleared my project before... So thaks for your great project and support!

**Comment by sharwell** [comment]
@lukemurray The attribute is included in the generated code because it's required for users who are compiling with `[assembly: CLSCompliant(true)]`. Explicitly setting the attribute to false is similar to ignoring it, except the compiler will be faster and it won't emit warnings if you include the attribute on types and/or members. I wish it was the default but for now it's something that needs to be manually applied.

**Comment by rustamm** [comment]
I had the same issue: The item "(omitted)Lexer.cs" was specified more than once in the "Sources" parameter. Duplicate items are not supported by the "Sources" parameter.

Installing the latest Visual Studio updates solved the problem.

**Comment by rustamm** [comment]
@sharwell The problem with duplicate sources still occurs if csproj file has CustomToolNamespace specified for Antlr4 items.

```
<ItemGroup>
    <Antlr4 Include="Routing\RequestFilter.g4">
      <Generator>MSBuild:Compile</Generator>
      <CustomToolNamespace>FrontendService.Routing.Generated</CustomToolNamespace>
    </Antlr4>
</ItemGroup>
```

I don't have this problem when I write like this:

```
<ItemGroup>
    <Antlr4 Include="Routing\RequestFilter.g4" />
</ItemGroup>
```

**Comment by sharwell** [comment]
@rustamm You need to use `Update=` instead of `Include=` 😄
