### PR TITLE
Package the .NET Standard version of the MSBuild tooling

### LINKED ISSUE #110: Parser does not compile with Antlr4.5 from homebrew
I'm on a mac. Have installed .NET using the instructions here https://github.com/aspnet/home

Used homebrew to install Antlr4. Which resolves to 4.5.

Compiling my generated files I get the following errors
error CS0534: 'MyParser' does not implement inherited abstract member 'Recognizer<IToken, ParserATNSimulator>.TokenNames.get'

MyParser.cs(437,41): error CS0103: The name 'TokenStream' does not exist in the current context

I can change TokenStream to _input and it resolves those errors, not sure about the other one.

I guess this might be an issue that the Nuget Antlr4.Runtime (how I reference this) is different to the one used in the released Antlr 4.5 version? Pretty sure .net on the mac is just Mono.

Any ideas?

Thanks

### LINKED ISSUE #167: Antlr4 doesn't support .NetCoreApp
Does Antlr4 support .NetCoreApp yet? as I am having several issues such  try to generate *g4 (which basically have lexer and parser classes but no help).
I have read almost all the articles on github regarding Antlr4/.NetCore but so far no help.

We are going to rewrite our app because of Antrl4 doesn't support .Net Core and we are bringing up full .net Framework. Are we going in the right direction? I tried everything but our .NetCore dependent solution doesn't seems to work with Antrl4.

java.exe : error(31):  ANTLR cannot generate CSharp_v4_5 code as of version 4.5.3At line:1 char:1
+ java -jar antlr-4.5.3-complete.jar *.g4 -o Generated -Dlanguage=CSharp_v4_5 -pac ...

http://stackoverflow.com/questions/41112478/antlr4-runtime-4-5-3-does-not-support-framework-netcoreapp-version-v1-0

### LINKED ISSUE #195: Antlr4Compile fails on TeamCity 10.0.5 w/ Microsoft Build Tools 2017: Could not load file or assembly Antlr4BuildTasks
I have converted one of my projects to the new `project.json` nuget reference format and upgraded the Antlr4 package to 4.6.1-beta002. The latter fixed the initial build issues I encountered in Visual Studio, but I'm still having trouble building this project in TeamCity:
> [Antlr4Compile] C:\Users\Services\.nuget\packages\antlr4.codegenerator\4.6.1-beta002\build\Antlr4.CodeGenerator.targets(110, 5): error MSB4062: The "Antlr4.Build.Tasks.Antlr4ClassGenerationTask" task could not be loaded from the assembly Antlr4BuildTasks, Version=4.0.0.0, Culture=neutral, PublicKeyToken=eb42632606e9261f. Could not load file or assembly 'Antlr4BuildTasks, Version=4.0.0.0, Culture=neutral, PublicKeyToken=eb42632606e9261f' or one of its dependencies. The system cannot find the file specified. Confirm that the <UsingTask> declaration is correct, that the assembly and all its dependencies are available, and that the task contains a public class that implements Microsoft.Build.Framework.ITask.

The assembly is present in the same folder: `C:\Users\Services\.nuget\packages\antlr4.codegenerator\4.6.1-beta002\build\Antlr4BuildTasks.dll`

The build server has Microsoft Build Tools 2017 installed as well as the SDKs and targeting packs for .NET Framework 4.5.1, 4.6.1, and 4.6.2. Any ideas about what I might be missing?

### LINKED ISSUE #208: Compilation Issues on .NET Core
I've posted this issue as comment to another issue, but in that conversation I've been informed the causes are different.

I am developing a SQL system ([DeveelDB](https://github.com/deveel/deveeldb.core)) based on .NET Core framework, using ANTLRv4 for the SQL parsing.
The project is a .NET Core with Visual Studio 2017 project model (MSBuild), targeting the version 1.1 of the framework: in all of my own machines (2 laptops and one desktop) the compilation and tests are all successful.

The peojects start to fail once built on [AppVeyor](https://ci.appveyor.com/project/Deveel/deveeldb-core/build/1.0.0-115) and [Travis](https://travis-ci.org/deveel/deveeldb.core/builds/245396700).

I've references all the libraries for the build (_Microsoft.Build.Framework v15.1.1012_, _Microsoft.Build.Tasks.Core v15.1.1012_ and _Microsoft.Build.Utilities.Core v15.1.1012_), without effects, as it is visible in the build log that can be seen in the CI linked

### PR DESCRIPTION
**Pull request by sharwell**
Fixes #208
Closes #195
Closes #167
Closes #110

### CODE REVIEW

**Comment by tsutomi** [comment]
I confirm it worked on Travis and Jenkins environment (Linux and OSX) and in AppVeyor (Windows). Thanks for the fix!
