### ISSUE TITLE
Parser does not compile with Antlr4.5 from homebrew

### ISSUE THREAD

**Issue by lukemurray** [tunnelvisionlabs/antlr4cs#110]
I'm on a mac. Have installed .NET using the instructions here https://github.com/aspnet/home

Used homebrew to install Antlr4. Which resolves to 4.5.

Compiling my generated files I get the following errors
error CS0534: 'MyParser' does not implement inherited abstract member 'Recognizer<IToken, ParserATNSimulator>.TokenNames.get'

MyParser.cs(437,41): error CS0103: The name 'TokenStream' does not exist in the current context

I can change TokenStream to _input and it resolves those errors, not sure about the other one.

I guess this might be an issue that the Nuget Antlr4.Runtime (how I reference this) is different to the one used in the released Antlr 4.5 version? Pretty sure .net on the mac is just Mono.

Any ideas?

Thanks

**Comment by sharwell** [comment]
### Reason for problems

ANTLR 4 includes two components which affect your use:

1. The code generator, which reads **.g4** files and creates **.cs** files.
1. The runtime library, which you compile against and then reference in your running application.

The underlying cause of your problem is the use of the runtime library from this project, but the use of the code generator from an unofficial (and incompatible) fork of the project.

Both of these components are distributed via NuGet packages. In addition, a fork of this project was created and distributed as a bundle with other targets ANTLR 4.5. That fork included a large number of breaking API changes which, if included in this build, would force upgrading users to make substantial changes to their applications. As a general policy I avoid requiring my users to do this, which means the fork of this project is not compatible with this target.

### Steps to a solution

I don't have a solution available for you immediately, because I don't know what build tools you are using. This target is designed to work automatically when used with MSBuild. Some users have suggested generating C# files from a grammar by using the command line, but this has proven unreliable for me and introduces an high probability that a developer's grammar and application will not match each other.

Can you describe the way your build system works to compile C# projects? Hopefully we can integrate directly with that build system so you just build and run and everything works.

**Comment by lukemurray** [comment]
That makes sense and is what I was thinking might be the issue.

I'm using ASP.NET vNext, which uses a new build system. It seems to just pick up CS files in the directory you are running from. Dependencies are defined in a project.json and resolved from nuget. Right now I just used Antlr4 command line to generate the parsers etc. and use dnx (https://github.com/aspnet/DNX) to run my application.

Looks like it supports pre-build scripts/tasks, see here https://github.com/aspnet/Home/wiki/Project.json-file#scripts.

That integration would be great but I don't need it right now. Is there a way to use this version of the code generator with the current installed Antlr? Or maybe it's easier to use the 4.5 bundled runtime? I ended up with this one because it is on Nuget and how dnx wants everything to be on nuget.

**Comment by sharwell** [comment]
### So this should be a start...

1. Add a reference to ANTLR 4 by adding the following to **project.json**:

    ```json
    {
      "dependencies": {
        "Antlr4": "4.5.0-alpha002"
      }
    }
    ```

1. Add references to **package.json**:

    ```json
    {
      "devDependencies": {
        "grunt": "0.4.5",
        "grunt-contrib-clean": "0.6.0",
        "grunt-run-java": "0.1.1"
      }
    }
    ```

1. Add a **gruntfile.js** to your project. This assumes your grammar is located in a folder **GrammarFolder**.

    ```js
    /// <binding BeforeBuild='run_java' Clean='clean' />

    module.exports = function (grunt) {
        grunt.initConfig({
            run_java: {
                antlr4_parsing: {
                    execOptions: {
                        cwd: 'GrammarFolder'
                    },
                    command: "java",
                    jarName: "/your-home/.dnx/packages/Antlr4/4.5-alpha002/tools/antlr4-csharp-4.5-SNAPSHOT-complete.jar",
                    javaArgs: "MyParser.g4 -Dlanguage=CSharp_v4_5 -package RootNamespace.GrammarFolder -o Generated"
                }
            },
            clean: [
                "GrammarFolder/Generated/"
            ]
        });

        grunt.loadNpmTasks("grunt-run-java");
        grunt.loadNpmTasks("grunt-contrib-clean");
    };
    ```

### Work left to do:

1. Automatically get the path to the **.dnx** folder
1. Automatically determine the correct version of the **Antlr4** package, and use that instead of hard-coding `4.5-alpha002`.
1. Automatically locate **\*\*/\*.g4** and generate them with the correct namespaces (the `-package` argument). This will also require a correct value for `RootNamespace`.
1. Automatically clean the grammar output folders. This means we should probably use a name for the generated output folder that won't conflict.

**Comment by lukemurray** [comment]
Thanks! That really helps. I didn't realise your version of the Antlr4 plugin (that generates the code) was on nuget.

That helps a lot!

**Comment by sharwell** [comment]
Starting with #209, the code generator will work across platforms.
